
# This file is automatically generated, you probably don't want to edit this

MEDIANTESTOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "MEDIANTESTOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            alt = "two.sided",
            testvalue = NULL,
            conf = 0.95, ...) {

            super$initialize(
                package="MEDIANTEST",
                name="MEDIANTEST",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..alt <- jmvcore::OptionList$new(
                "alt",
                alt,
                options=list(
                    "two.sided",
                    "greater",
                    "less"),
                default="two.sided")
            private$..testvalue <- jmvcore::OptionNumber$new(
                "testvalue",
                testvalue)
            private$..conf <- jmvcore::OptionNumber$new(
                "conf",
                conf,
                min=0,
                max=1,
                default=0.95)

            self$.addOption(private$..dep)
            self$.addOption(private$..alt)
            self$.addOption(private$..testvalue)
            self$.addOption(private$..conf)
        }),
    active = list(
        dep = function() private$..dep$value,
        alt = function() private$..alt$value,
        testvalue = function() private$..testvalue$value,
        conf = function() private$..conf$value),
    private = list(
        ..dep = NA,
        ..alt = NA,
        ..testvalue = NA,
        ..conf = NA)
)

MEDIANTESTResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "MEDIANTESTResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        mediantest = function() private$.items[["mediantest"]],
        medianci = function() private$.items[["medianci"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Test and Confidence Intervals for the Median")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Test and Confidence Intervals for the Median"))
            self$add(jmvcore::Table$new(
                options=options,
                name="mediantest",
                title="Median test",
                rows=1,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Median", 
                        `type`="number"),
                    list(
                        `name`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="Lower", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="medianci",
                title="Confidence Intervals for Median",
                rows=3,
                columns=list(
                    list(
                        `name`="type", 
                        `title`="Type", 
                        `type`="text"),
                    list(
                        `name`="ConfLevel", 
                        `title`="Confidence Level", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `title`="Lower Limit", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `title`="Upper Limit", 
                        `type`="number"))))}))

MEDIANTESTBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "MEDIANTESTBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "MEDIANTEST",
                name = "MEDIANTEST",
                version = c(1,0,0),
                options = options,
                results = MEDIANTESTResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Test and Confidence Intervals for the Median
#'
#' 
#' @param data .
#' @param dep .
#' @param alt .
#' @param testvalue .
#' @param conf .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$mediantest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$medianci} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$mediantest$asDF}
#'
#' \code{as.data.frame(results$mediantest)}
#'
#' @export
MEDIANTEST <- function(
    data,
    dep,
    alt = "two.sided",
    testvalue,
    conf = 0.95) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("MEDIANTEST requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL))


    options <- MEDIANTESTOptions$new(
        dep = dep,
        alt = alt,
        testvalue = testvalue,
        conf = conf)

    analysis <- MEDIANTESTClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

